---
- hosts: localhost

  tasks:
    - name: Install basics
      become: yes
      apt:
        pkg:
          - software-properties-common
          - build-essential
          - git
          - fonts-jetbrains-mono
          - tmux
          - stow
        state: latest
        update_cache: yes

    # Remove Firefox
    - name: Remove Firefox
      become: yes
      apt:
        name: firefox
        state: absent

    # Install Chrome
    - name: Add Chrome Apt signing key
      become: yes
      apt_key:
        url: "https://dl.google.com/linux/linux_signing_key.pub"
        state: present

    - name: Add Chrome repository into sources list
      become: yes
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install google-chrome-stable
      become: yes
      apt:
        name: google-chrome-stable
        state: latest
        update_cache: yes

    # Install AppImageLauncher
    - name: Add AppImageLauncher repository into sources list
      become: yes
      apt_repository:
        repo: ppa:appimagelauncher-team/stable
        state: present

    - name: Install AppImageLauncher
      become: yes
      apt:
        name: appimagelauncher
        state: latest
        update_cache: yes

    - name: Create ~/Applications directory
      file:
        path: "{{ ansible_env.HOME }}/Applications"
        state: directory

    # Install WezTerm
    - name: Install WezTerm
      get_url:
        url: https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/WezTerm-20221119-145034-49b9839f-Ubuntu18.04.AppImage
        dest: "{{ ansible_env.HOME }}/Applications/WezTerm"
        mode: a+x

    # Install and configure zsh
    - name: Install zsh
      become: yes
      apt:
        pkg: zsh
        state: latest
        update_cache: yes

    - name: Change user shell to zsh 
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    # Install and configure tmux
    - name: Install tmux
      become: yes
      apt:
        pkg: tmux
        state: latest
        update_cache: yes

    - name: Create ~/.tmux/plugins/tpm directory
      file:
        path: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        state: directory

    - name: Install Tmux Plugin Manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

    # Install Neovim
    - name: Install Neovim
      become: yes
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        dest: /usr/bin/nvim
        owner: root
        group: root
        mode: a+x

    - name: Create vim-plug directory
      file:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
        state: directory

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

    # Clone and symlink dotfiles
    - name: Clone dotfiles
      git:
        repo: https://github.com/imryche/dotfiles
        dest: "{{ ansible_env.HOME }}/dotfiles"

    - name: Stow dotfiles
      shell:
        chdir: "{{ ansible_env.HOME }}/dotfiles"
        cmd: "stow wezterm zsh tmux nvim sqlite"

    # Install Python
    - name: Add deadsnakes repository into sources list
      become: yes
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Install system Python packages
      become: yes
      apt:
        pkg:
          - python3-pip
          - python3-dev
          - python3.11
          - python3.11-dev
          - python-is-python3
        state: latest
        update_cache: yes

    - name: Install virtualenvwrapper
      become: yes
      pip:
        name: virtualenvwrapper
