onboarding = false
[theme]
name = "terminal"

[theme.custom]
panel_bg = "black"

[terminal]
new_cwd = "follow"

[keys]
prefix = "ctrl+space"

new_tab = "alt+t"
rename_tab = "alt+r"
goto = "alt+d"
next_tab = "alt+n"
previous_tab = "alt+p"
switch_tab = "alt+1..9"
focus_agent = "alt+shift+1..9"
split_vertical = "alt+v"
split_horizontal = "alt+s"
focus_pane_right = "alt+l"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
close_pane = "alt+w"

[ui]
accent = "blue"
pane_gaps = false
pane_outer_borders = false
pane_scrollbars = false
confirm_close = false
prompt_new_tab_name = false
mouse_capture = true
tab_bar_right = [{ type = "zoom" }, { type = "hostname" }]
window_title = "{hostname}: {workspace}"

[experimental]
kitty_graphics = true
